<?php

namespace AppBundle\Repository;

/**
 * CommandeProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeProductRepository extends \Doctrine\ORM\EntityRepository
{
}
