# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider:             fos_userbundle
                login_path:           fos_user_security_login
                check_path:           fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   fos_user_security_logout
                target: /
            anonymous: true
            access_denied_handler: AppBundle\Security\AccessDeniedHandler

    access_control:
        - { path: ^/(en|fr)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/admin/, role: ROLE_ADMIN }
        - { path: ^/(en|fr)/app, role: ROLE_USER }

