services:
#surcharge registration form fosuserbundle
    app.form.registration.type:
        class: UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_registration }

